name: Compile MicroPython Firmware

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: 'Compile MicroPython Firmware via docker'
      env:
        PIPENV_NOSPIN: 1
      run: |
        python3 -m pip install --upgrade pipenv
        make compile-firmware
        ls -la build/
        file build/firmware-ota.bin

